MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_test",)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.001    
  WARMUP_ITERS: 1336
  STEPS: (54776, 81496)
  MAX_ITER: 94856
INPUT:
  MIN_SIZE_TRAIN: (432,864)
  MASK_FORMAT: "bitmask"
VERSION: 2


